package com.example.util

import android.content.Context
import android.os.Build
import android.print.PrintAttributes
import android.print.PrintManager
import android.webkit.WebView
import android.webkit.WebViewClient
import android.widget.Toast
import com.example.data.model.LanguageMode

object PdfPrintHelper {

    fun printTimelineReport(
        context: Context,
        timelineData: AccountTimelineData,
        displayCurrency: Boolean = true,
        languageMode: LanguageMode = LanguageMode.ENGLISH
    ) {
        val htmlContent = buildTimelineHtml(timelineData, displayCurrency, languageMode)
        printHtml(context, "Accounts_Balances_Over_Time", htmlContent)
    }

    fun printHtml(context: Context, jobName: String, htmlContent: String, isLandscape: Boolean = false) {
        try {
            val webView = WebView(context)
            webView.webViewClient = object : WebViewClient() {
                override fun onPageFinished(view: WebView?, url: String?) {
                    super.onPageFinished(view, url)
                    val printManager = context.getSystemService(Context.PRINT_SERVICE) as? PrintManager
                    if (printManager != null) {
                        val printAdapter = webView.createPrintDocumentAdapter(jobName)
                        val mediaSize = if (isLandscape) {
                            PrintAttributes.MediaSize.ISO_A4.asLandscape()
                        } else {
                            PrintAttributes.MediaSize.ISO_A4.asPortrait()
                        }
                        val builder = PrintAttributes.Builder()
                            .setMediaSize(mediaSize)
                            .setMinMargins(PrintAttributes.Margins.NO_MARGINS)
                            .setColorMode(PrintAttributes.COLOR_MODE_COLOR)
                        printManager.print(jobName, printAdapter, builder.build())
                    } else {
                        Toast.makeText(context, "Print service not available", Toast.LENGTH_SHORT).show()
                    }
                }
            }
            webView.loadDataWithBaseURL(null, htmlContent, "text/html", "UTF-8", null)
        } catch (e: Exception) {
            Toast.makeText(context, "Error generating report: ${e.localizedMessage}", Toast.LENGTH_LONG).show()
        }
    }

    fun buildTimelineHtml(
        data: AccountTimelineData,
        displayCurrency: Boolean,
        languageMode: LanguageMode
    ): String {
        val title = if (languageMode == LanguageMode.BANGLA) "সময়ের সাথে অ্যাকাউন্টের ব্যালেন্স" else "Accounts Balances Over Time"
        val currencySymbol = if (displayCurrency) "৳ " else ""

        val sb = StringBuilder()
        sb.append("""
            <!DOCTYPE html>
            <html>
            <head>
                <meta charset="utf-8">
                <style>
                    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; margin: 20px; color: #1e293b; }
                    h1 { font-size: 20px; margin-bottom: 4px; color: #0f172a; }
                    .subtitle { font-size: 12px; color: #64748b; margin-bottom: 16px; }
                    table { width: 100%; border-collapse: collapse; font-size: 11px; }
                    th, td { padding: 6px 10px; border-bottom: 1px solid #e2e8f0; text-align: right; }
                    th:first-child, td:first-child { text-align: left; }
                    th { background-color: #f8fafc; font-weight: 600; color: #475569; border-top: 1px solid #cbd5e1; border-bottom: 2px solid #cbd5e1; }
                    .section-assets { background-color: #dcfce7; font-weight: bold; color: #15803d; }
                    .section-liabilities { background-color: #fee2e2; font-weight: bold; color: #b91c1c; }
                    .group-row { font-weight: 600; color: #334155; background-color: #f8fafc; }
                    .sub-row { color: #475569; padding-left: 24px; }
                    .net-worth-row { background-color: #f1f5f9; font-weight: bold; font-size: 12px; border-top: 2px solid #94a3b8; border-bottom: 2px solid #94a3b8; }
                    .positive { color: #15803d; }
                    .negative { color: #b91c1c; }
                    .footer { margin-top: 20px; font-size: 10px; color: #94a3b8; text-align: right; }
                </style>
            </head>
            <body>
                <h1>$title</h1>
                <div class="subtitle">Generated by Budgeter &bull; ${DateUtils.formatDate(System.currentTimeMillis(), languageMode)}</div>
                <table>
                    <thead>
                        <tr>
                            <th>${if (languageMode == LanguageMode.BANGLA) "অ্যাকাউন্ট" else "Account"}</th>
        """.trimIndent())

        for (p in data.periods) {
            sb.append("<th>${p.shortLabel}</th>")
        }
        sb.append("</tr></thead><tbody>")

        // 1. Assets Section Header
        sb.append("<tr class=\"section-assets\">")
        sb.append("<td>${if (languageMode == LanguageMode.BANGLA) "সম্পদ (Assets)" else "Assets"}</td>")
        for (amt in data.totalAssetsByPeriod) {
            sb.append("<td>$currencySymbol${LanguageHelper.formatNumber(amt, languageMode)}</td>")
        }
        sb.append("</tr>")

        // Asset Groups & Sub-Accounts
        for (group in data.assetGroups) {
            val groupName = if (languageMode == LanguageMode.BANGLA) group.parentAccount.nameBn else group.parentAccount.nameEn
            sb.append("<tr class=\"group-row\">")
            sb.append("<td>&gt; $groupName</td>")
            for (amt in group.groupBalances) {
                sb.append("<td>$currencySymbol${LanguageHelper.formatNumber(amt, languageMode)}</td>")
            }
            sb.append("</tr>")

            for (sub in group.subAccounts) {
                val subName = if (languageMode == LanguageMode.BANGLA) sub.account.nameBn else sub.account.nameEn
                sb.append("<tr class=\"sub-row\">")
                sb.append("<td style=\"padding-left: 20px;\">&bull; $subName</td>")
                for (amt in sub.balances) {
                    sb.append("<td>$currencySymbol${LanguageHelper.formatNumber(amt, languageMode)}</td>")
                }
                sb.append("</tr>")
            }
        }

        // 2. Liabilities Section Header
        sb.append("<tr class=\"section-liabilities\">")
        sb.append("<td>${if (languageMode == LanguageMode.BANGLA) "দায় (Liabilities)" else "Liabilities"}</td>")
        for (amt in data.totalLiabilitiesByPeriod) {
            sb.append("<td>$currencySymbol${LanguageHelper.formatNumber(amt, languageMode)}</td>")
        }
        sb.append("</tr>")

        // Liability Groups & Sub-Accounts
        for (group in data.liabilityGroups) {
            val groupName = if (languageMode == LanguageMode.BANGLA) group.parentAccount.nameBn else group.parentAccount.nameEn
            sb.append("<tr class=\"group-row\">")
            sb.append("<td>&gt; $groupName</td>")
            for (amt in group.groupBalances) {
                sb.append("<td>$currencySymbol${LanguageHelper.formatNumber(amt, languageMode)}</td>")
            }
            sb.append("</tr>")

            for (sub in group.subAccounts) {
                val subName = if (languageMode == LanguageMode.BANGLA) sub.account.nameBn else sub.account.nameEn
                sb.append("<tr class=\"sub-row\">")
                sb.append("<td style=\"padding-left: 20px;\">&bull; $subName</td>")
                for (amt in sub.balances) {
                    sb.append("<td>$currencySymbol${LanguageHelper.formatNumber(amt, languageMode)}</td>")
                }
                sb.append("</tr>")
            }
        }

        // 3. Net Worth Row
        sb.append("<tr class=\"net-worth-row\">")
        sb.append("<td>${if (languageMode == LanguageMode.BANGLA) "নেট সম্পদ (Net Worth)" else "Net Worth"}</td>")
        for (amt in data.netWorthByPeriod) {
            val cls = if (amt >= 0) "positive" else "negative"
            sb.append("<td class=\"$cls\">$currencySymbol${LanguageHelper.formatNumber(amt, languageMode)}</td>")
        }
        sb.append("</tr>")

        sb.append("""
                    </tbody>
                </table>
                <div class="footer">Budgeter &bull; Personal Finance Double-Entry Ledger</div>
            </body>
            </html>
        """.trimIndent())

        return sb.toString()
    }
}
