import {
  Account,
  AccountType,
  Category,
  CategoryType,
  Transaction,
  TransactionType,
  TransactionStatus,
  MonthlyBudget,
  RecurringBill,
  BillFrequency,
} from '../types';

export const DEFAULT_ACCOUNTS: Account[] = [
  {
    id: 1,
    nameEn: 'Cash Wallet',
    nameBn: 'নগদ টাকা (ক্যাশ)',
    type: AccountType.ASSET,
    initialBalance: 5205,
    iconName: 'Wallet',
    colorHex: '#10B981',
    isArchived: false,
    sortOrder: 1,
    parentId: null,
    accountRole: 'Cash & Wallets',
    isCalculated: true,
    calculationAdjustment: 0,
  },
  {
    id: 2,
    nameEn: 'Sonali Bank',
    nameBn: 'সোনালী ব্যাংক হিসাব',
    type: AccountType.ASSET,
    initialBalance: 6640.3,
    iconName: 'Building2',
    colorHex: '#3B82F6',
    isArchived: false,
    sortOrder: 2,
    parentId: null,
    accountRole: 'Sonali Bank Group',
    isCalculated: true,
    calculationAdjustment: 0,
  },
  {
    id: 3,
    nameEn: 'bKash',
    nameBn: 'বিকাশ ওয়ালেট',
    type: AccountType.ASSET,
    initialBalance: 12500,
    iconName: 'Smartphone',
    colorHex: '#EC4899',
    isArchived: false,
    sortOrder: 3,
    parentId: null,
    accountRole: 'Mobile Banking Accounts',
    isCalculated: true,
    calculationAdjustment: 0,
  },
  {
    id: 4,
    nameEn: 'Sakib',
    nameBn: 'সাকিব (ব্যক্তিগত)',
    type: AccountType.ASSET,
    initialBalance: 160,
    iconName: 'User',
    colorHex: '#8B5CF6',
    isArchived: false,
    sortOrder: 4,
    parentId: null,
    accountRole: 'Personal Accounts',
    isCalculated: true,
    calculationAdjustment: 0,
  },
  {
    id: 5,
    nameEn: 'Visa Credit Card',
    nameBn: 'ভিসা ক্রেডিট কার্ড',
    type: AccountType.LIABILITY,
    initialBalance: 18500,
    iconName: 'CreditCard',
    colorHex: '#EF4444',
    isArchived: false,
    sortOrder: 5,
    parentId: null,
    accountRole: 'Credit Cards',
    isCalculated: true,
    calculationAdjustment: 0,
  },
];

export const DEFAULT_CATEGORIES: Category[] = [
  // Parent & Sub Categories (Expense)
  {
    id: 1,
    nameEn: 'Utilities',
    nameBn: 'ইউটিলিটি ও বিল',
    type: CategoryType.EXPENSE,
    iconName: 'Zap',
    colorHex: '#6366F1',
    monthlyBudget: 6000,
    sortOrder: 1,
    parentId: null,
    isTaxDeductible: false,
    defaultAccountId: 3,
    isCalculated: true,
  },
  {
    id: 11,
    nameEn: 'Mobile Recharge',
    nameBn: 'মোবাইল রিচার্জ',
    type: CategoryType.EXPENSE,
    iconName: 'Phone',
    colorHex: '#6366F1',
    monthlyBudget: 1500,
    sortOrder: 2,
    parentId: 1,
    isTaxDeductible: false,
    defaultAccountId: 3,
    isCalculated: true,
  },
  {
    id: 2,
    nameEn: 'Home Snacks & Sweets',
    nameBn: 'ঘরের নাস্তা ও মিষ্টি',
    type: CategoryType.EXPENSE,
    iconName: 'Utensils',
    colorHex: '#F59E0B',
    monthlyBudget: 8000,
    sortOrder: 3,
    parentId: null,
    isTaxDeductible: false,
    defaultAccountId: 1,
    isCalculated: true,
  },
  {
    id: 3,
    nameEn: 'Students',
    nameBn: 'ছাত্র-ছাত্রী / টিউশন',
    type: CategoryType.EXPENSE,
    iconName: 'GraduationCap',
    colorHex: '#8B5CF6',
    monthlyBudget: 3500,
    sortOrder: 4,
    parentId: null,
    isTaxDeductible: false,
    defaultAccountId: 1,
    isCalculated: true,
  },
  {
    id: 4,
    nameEn: 'Bank Charges',
    nameBn: 'ব্যাংক চার্জ ও ফি',
    type: CategoryType.EXPENSE,
    iconName: 'CreditCard',
    colorHex: '#0ea5e9',
    monthlyBudget: 1000,
    sortOrder: 5,
    parentId: null,
    isTaxDeductible: false,
    defaultAccountId: 2,
    isCalculated: true,
  },
  {
    id: 14,
    nameEn: 'Transfer Charges',
    nameBn: 'স্থানান্তর চার্জ (ফি)',
    type: CategoryType.EXPENSE,
    iconName: 'ArrowLeftRight',
    colorHex: '#0ea5e9',
    monthlyBudget: 500,
    sortOrder: 6,
    parentId: 4,
    isTaxDeductible: false,
    defaultAccountId: 2,
    isCalculated: true,
  },
  {
    id: 5,
    nameEn: 'Others',
    nameBn: 'অন্যান্য',
    type: CategoryType.EXPENSE,
    iconName: 'MoreHorizontal',
    colorHex: '#64748b',
    monthlyBudget: 2000,
    sortOrder: 7,
    parentId: null,
    isTaxDeductible: false,
    defaultAccountId: 1,
    isCalculated: true,
  },
  {
    id: 6,
    nameEn: 'Housing & Rent',
    nameBn: 'বাড়ি ভাড়া ও আবাসন',
    type: CategoryType.EXPENSE,
    iconName: 'Home',
    colorHex: '#3B82F6',
    monthlyBudget: 25000,
    sortOrder: 8,
    parentId: null,
    isTaxDeductible: false,
    defaultAccountId: 2,
    isCalculated: true,
  },

  // Income Categories
  {
    id: 8,
    nameEn: 'Monthly Salary',
    nameBn: 'মাসিক বেতন',
    type: CategoryType.INCOME,
    iconName: 'Briefcase',
    colorHex: '#10B981',
    monthlyBudget: 85000,
    sortOrder: 9,
    parentId: null,
    isTaxDeductible: false,
    defaultAccountId: 2,
    isCalculated: true,
  },
  {
    id: 9,
    nameEn: 'Freelance & Projects',
    nameBn: 'ফ্রিল্যান্সিং ও কনসাল্টিং',
    type: CategoryType.INCOME,
    iconName: 'Laptop',
    colorHex: '#06B6D4',
    monthlyBudget: 25000,
    sortOrder: 10,
    parentId: null,
    isTaxDeductible: false,
    defaultAccountId: 2,
    isCalculated: true,
  },
  {
    id: 10,
    nameEn: 'Investment Returns',
    nameBn: 'বিনিয়োগ ও লভ্যাংশ',
    type: CategoryType.INCOME,
    iconName: 'TrendingUp',
    colorHex: '#84CC16',
    monthlyBudget: 5000,
    sortOrder: 11,
    parentId: null,
    isTaxDeductible: false,
    defaultAccountId: 4,
    isCalculated: true,
  },
];

const now = Date.now();
const dayMs = 24 * 60 * 60 * 1000;

export const DEFAULT_TRANSACTIONS: Transaction[] = [
  {
    id: 1,
    type: TransactionType.INCOME,
    amount: 85000,
    dateEpochMs: now - 3 * dayMs,
    creditAccountId: null,
    debitAccountId: 2, // Bank Account Inflow
    categoryId: 8,     // Salary
    note: 'September primary salary credited',
    payeePayer: 'Acme Technologies Ltd',
    status: TransactionStatus.CLEARED,
    labelIds: [1],
    tags: ['salary', 'income'],
  },
  {
    id: 2,
    type: TransactionType.EXPENSE,
    amount: 25000,
    dateEpochMs: now - 2 * dayMs,
    creditAccountId: 2, // From Bank
    debitAccountId: null,
    categoryId: 2,      // Rent
    note: 'Apartment monthly rent payment',
    payeePayer: 'Landlord Mr. Rahman',
    status: TransactionStatus.CLEARED,
    labelIds: [2],
    tags: ['rent', 'fixed'],
  },
  {
    id: 3,
    type: TransactionType.EXPENSE,
    amount: 4200,
    dateEpochMs: now - 1 * dayMs,
    creditAccountId: 1, // From Cash
    debitAccountId: null,
    categoryId: 1,      // Food & Groceries
    note: 'Weekly fresh vegetables & meat market',
    payeePayer: 'Agora Superstore',
    status: TransactionStatus.CLEARED,
    labelIds: [],
    tags: ['groceries', 'household'],
  },
  {
    id: 4,
    type: TransactionType.EXPENSE,
    amount: 2200,
    dateEpochMs: now - 12 * 60 * 60 * 1000,
    creditAccountId: 3, // bKash
    debitAccountId: null,
    categoryId: 3,      // Utilities
    note: 'Fiber high-speed broadband monthly bill',
    payeePayer: 'Amber IT Internet',
    status: TransactionStatus.CLEARED,
    labelIds: [],
    tags: ['wifi', 'bills'],
  },
  {
    id: 5,
    type: TransactionType.TRANSFER,
    amount: 10000,
    dateEpochMs: now - 6 * 60 * 60 * 1000,
    creditAccountId: 2, // From Bank
    debitAccountId: 4,  // To Emergency Savings
    categoryId: null,
    note: 'Monthly emergency savings deposit',
    payeePayer: 'Self Transfer',
    status: TransactionStatus.CLEARED,
    labelIds: [],
    tags: ['savings', 'transfer'],
  },
  {
    id: 6,
    type: TransactionType.EXPENSE,
    amount: 3100,
    dateEpochMs: now - 2 * 60 * 60 * 1000,
    creditAccountId: 5, // Visa Card
    debitAccountId: null,
    categoryId: 6,      // Entertainment & Shopping
    note: 'Family dinner outing',
    payeePayer: 'Cafe Rio',
    status: TransactionStatus.UNCLEARED,
    labelIds: [],
    tags: ['dining', 'leisure'],
  },
];

const curDate = new Date();
const currentYear = curDate.getFullYear();
const currentMonth = curDate.getMonth() + 1;

export const DEFAULT_MONTHLY_BUDGETS: MonthlyBudget[] = DEFAULT_CATEGORIES
  .filter((c) => c.type === CategoryType.EXPENSE)
  .map((cat, idx) => ({
    id: idx + 1,
    categoryId: cat.id,
    year: currentYear,
    month: currentMonth,
    budgetAmount: cat.monthlyBudget,
    isRolloverEnabled: true,
  }));

export const DEFAULT_RECURRING_BILLS: RecurringBill[] = [
  {
    id: 1,
    title: 'High-Speed Broadband WiFi',
    amount: 2200,
    frequency: BillFrequency.MONTHLY,
    nextDueDateEpochMs: now + 5 * dayMs,
    categoryId: 3,
    accountId: 3,
    isAutoPaid: false,
    isActive: true,
    reminderDaysBefore: 3,
  },
  {
    id: 2,
    title: 'Apartment Monthly Rent',
    amount: 25000,
    frequency: BillFrequency.MONTHLY,
    nextDueDateEpochMs: now + 12 * dayMs,
    categoryId: 2,
    accountId: 2,
    isAutoPaid: true,
    isActive: true,
    reminderDaysBefore: 5,
  },
  {
    id: 3,
    title: 'Electricity & Utility DESCO',
    amount: 3500,
    frequency: BillFrequency.MONTHLY,
    nextDueDateEpochMs: now + 8 * dayMs,
    categoryId: 3,
    accountId: 3,
    isAutoPaid: false,
    isActive: true,
    reminderDaysBefore: 2,
  },
];
